### ISSUE TITLE
Nginx container restarts with `could not build server_names_hash` error

### ISSUE THREAD

**Issue by kbitr** [regisb/tutor#115]
When making tutor (make all), due to my long domain names, the nginx keeps restarting. The container log says `could not build server_names_hash, you should increase server_names_hash_bucket_size: 32`. That should be solved by setting `server_names_hash_bucket_size  64;` in the http config blog.

Question: Where is the appropriate config file of tutors nginx to do so?

**Comment by regisb** [comment]
The nginx configuration files in `deploy/env/nginx` are generated from the templates in `deploy/templates/nginx` whenever you run `make configure` (or `make env`). I managed to reproduce your issue. To fix this issue, we need to override the `/etc/nginx/nginx.conf` file inside the nginx container and add the following line to it:

    server_names_hash_bucket_size 64;

Currently, we do not override the `nginx.conf` file, so we need to add the `deploy/templates/nginx.conf` with the following content:

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server_names_hash_bucket_size 64;

    include /etc/nginx/conf.d/*.conf;
}
```

And then we need to change the way nginx volumes are mounted inside the nginx container in the `deploy/local/templates/docker-compose.yml` file.

Would you like to do this or should I take care of it?

**Comment by kbitr** [comment]
@regisb Perfect! Did you mean `deploy/templates/nginx/nginx.conf` instead of `deploy/templates/nginx.conf` or was this no typo?

Yes, a little advice would be nice! What change is necessary in the `nginx: volumes:` part?

**Comment by regisb** [comment]
>  Did you mean deploy/templates/nginx/nginx.conf instead of deploy/templates/nginx.conf or was this no typo?

Yes, you're right :) Editing my answer now.

> What change is necessary in the nginx: volumes: part?

Probably something like:

```
nginx:
    ...
    volumes:
      - ../env/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../env/nginx/conf.d:/etc/nginx/conf.d/
      - ../../data/openedx:/var/www/openedx:ro
      - ../../data/letsencrypt:/etc/letsencrypt/:ro
```

Note that the `deploy/templates/nginx/*.conf` files will have to be moved to `deploy/templates/nginx/conf.d`.

**Comment by kbitr** [comment]
Alright.

mkdir deploy/templates/nginx/conf.d
mv deploy/templates/nginx/*.conf deploy/templates/nginx/conf.d
write your config to deploy/templates/nginx/nginx.conf


Though, that didn't work. But I do not know how to confirm the config was copied correctly, since I do not know how to look into the container while it is restarting.

Anyway, when do I have to use which command? Most of the time I do not know when to use `make all`, `make run`, `make daemonize` and I just make all.

**Comment by regisb** [comment]
Well, when you mount a volume in /etc/nginx, then all files from this folder are overwritten. And there are many (potentially useful) files there:

```
ls /etc/nginx/
conf.d  fastcgi_params  koi-utf  koi-win  mime.types  modules  nginx.conf  scgi_params  uwsgi_params  win-utf
```

I think your changes deserve a pull request. I'll re-open this and work on a more temporary fix, if you don't mind.

**Comment by kbitr** [comment]
Just to not start confusion. Will you edit this or should I start a pull request?

**Comment by regisb** [comment]
I think I found an elegant fix. Can you confirm it works for you?

**Comment by kbitr** [comment]
Can't check right now, I will report as soon as I will redeploy the whole thing. But since this is a very basic fix and nginx reads the config from there, it should be fine.
