### ISSUE TITLE
error: error reading ../env/nginx: no such file or directory

### ISSUE THREAD

**Issue by natea** [regisb/tutor#116]
PLEASE PLEASE PLEASE READ THIS AND FOLLOW THE INSTRUCTIONS WHEN OPENING A NEW ISSUE

## Steps to reproduce

I'm following the instructions here: http://docs.tutor.overhang.io/en/latest/k8s.html

## Unexpected behavior

When I run the `make all` command, I get this error:

```
nateaune at natemacbookpro in ~/Documents/code/tutor/deploy/k8s (master)
$ make all
kubectl create -f namespace.yml

namespace "openedx" created
kubectl create configmap nginx-config --from-file=../env/nginx --namespace=openedx
error: error reading ../env/nginx: no such file or directory
make: *** [config] Error 1
```

**Comment by regisb** [comment]
Nate, I can help you solve this issue, but I'm afraid you would get stuck again on another bug further down the road... I'm sorry, I should probably mention in the documentation that k8s deployment does not work yet :-/ When I wrote "alpha feature" in the documentation I truly thought that I could get it to work in a few days, but things got in the way. I hope I can get k8s working before the end of the weekend. Meanwhile, you can try to solve your particular problem by running `make env` in the `deploy` folder.

**Comment by natea** [comment]
ok, i'll just wait until you give the green light that it's ready for further testing. good luck this weekend! :)

**Comment by regisb** [comment]
Phew! Just shy of one hour before the end of the weekend ;) can you try again @natea? The docs were updated, too: http://docs.tutor.overhang.io/en/latest/k8s.html

**Comment by natea** [comment]
Just tried and got past this issue, but then encountered another one (as you predicted) ;) 
I'll open a separate ticket for that one.
