### ISSUE TITLE
Failed to connect to mysql 

### ISSUE THREAD

**Issue by efatuarte95** [regisb/tutor#120]
## Steps to reproduce

I have just cloned the repo following the steps included in the guide:
```
git clone https://github.com/regisb/tutor
cd tutor/deploy/local
make all
```
## Unexpected behavior

It is supposed that when i exec ```make all```, the docker images are pulled and run immediately but this error appears:
```
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for MySQL database to be ready...
MySQL: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for MySQL database to be ready...
MySQL: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for MySQL database to be ready...
MySQL: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for MySQL database to be ready...
```

## Additional info (IMPORTANT)

I have just watched a similar issue (#75 & #51) here where the following commands are recommended:
```
make stop
make databases
```
But when i run them instead of solving the problem the same error appears again...

Any help would be appreciated

**Comment by regisb** [comment]
Hi @efatuarte95! Can you please paste here the complete output of `make databases`?

**Comment by efatuarte95** [comment]
I finally solved the issue using
```docker-compose down``` to drop all my docker containers and images and then with
```docker system prune --volumes``` I deleted my volumes.
Then I run make all again and it worked! I don't know really what happened but now everything it's fine.

**Comment by regisb** [comment]
Awesome! Good job solving that on your own ;)
