### ISSUE TITLE
Discuss docker image name-spacing

### ISSUE THREAD

**Issue by frob** [regisb/tutor#122]
I opened #108 to try and allow more flexibility of developers/vendors to use this without needing to behold to the originally defined images. With the recent changes to the project it would take significant refactoring to re-roll that patch. Therefore, I feel some discussion should happen first to clarify the goal and gain acceptance before I spend hours working toward something that isn't desired.

**Comment by frob** [comment]
My proposal for this has these goals:

- Allow easier tagging of images for release
- Allow custom namespaces for image building
- Allow custom distinct names for images

All of the above should be: 

- fully independent (meaning changing the tag shouldn't effect the namespace)
- fully functional (meaning that changing any of the above shouldn't break any existing functionality, with the exception of push with regard to permissions)

**Comment by regisb** [comment]
As part of solving issue #121, I am currently working on a single `tutor` executable to replace most `make` commands. The way I see it, this executable will take a `config.yml` configuration file as argument. This configuration file will contain much richer information than the current `config.json` file. In particular, we should be able to write something along the lines of:

```
local:
   ...
    openedx:
        image: username/imagename:tag
        ...
```

This would override the name and tag of the openedx image. I believe that would solve most of you problem, right? I still need to figure out of to simplify the image building, though.

**Comment by regisb** [comment]
Hey @frob! I finally took the time to address this. Please let me know if the chosen solution is satisfactory. There were different ways to solve this, I picked the solution that would satisfy most people (IMHO).
