### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by DiegoGallegos4** [regisb/tutor#125]
## Steps to reproduce
Run:
`make all`

## Unexpected behavior

This command is not on the Makefile anymore.

## Additional info (IMPORTANT)

This command suggested on opening a new ticket also is not working:
> Include the output of the `make info` command.

**Comment by regisb** [comment]
Hi @DiegoGallegos4! Have you tried `cd tutor/deploy/local` prior to running `make all` ?

**Comment by DiegoGallegos4** [comment]
You are right @regisb my bad, sorry for the noise.

**Comment by regisb** [comment]
No worries :) And I moved the `make info` command to the root folder.
