### ISSUE TITLE
Streamline Containers

### ISSUE THREAD

**Issue by frob** [regisb/tutor#127]
## Steps to reproduce

run `make build`

## Unexpected behavior

Building images takes a very long time and leaves us with very large containers --over a 2GB.

## Proposed solution

If we streamline the build to use a common base image layer for all the edx-platform based images then that will reduce the pull time and the only thing that will build will be the custom layers. I also think more work can be done by using alpine based images instead of ubuntu:16.04

This will likely require more work to get it working, but once working this should result in a much faster build and a much smaller image.

**Comment by frob** [comment]
> First of all, "faster" and "lighter" are two completely different issues. I'd dare to say, they are even incompatible.

I agree they are different, but I don't agree they are incompatible. Also, I think the faster part needs more clarification. I think the builds can be made faster. I also think that we can make the download faster as well, but we will see.

About those benchmarks. The numbers are great starting points, but I am not sure they mean that the image is just going to be big. Looking at the docker python images:

```
python                                2.7                 bfa54426aeda        9 days ago          912MB
python                                3.6                 55fb8aca33df        9 days ago          922MB
python                                3.6-alpine          1837080c5e87        3 weeks ago         74.4MB
python                                2.7-alpine          66c225e226f9        4 weeks ago         58.3MB
```

Looking at these images as a baseline of improvements that can be made, aside from the static assets, I think we can shrink the image down considerably. 

I also think there is some low hanging fruit. I know that edx-platform is built (so far) to only work with Ubuntu 16.04, but there are other images that we can start with.

- **Forum** : ruby based: ubuntu:18.04
- **Notes** : python based: ubuntu:18.04
- **XQueue** : python based: ubuntu:18.04

I am less worried about android because that is used for development and the image should never be deployed.

As I think through the process for streamlining all this it begs a question. What about testing. That might be a first step to make sure something obscure isn't broken by these changes. Opened #129 to discuss testing.

**Comment by frob** [comment]
@regisb I was going to see if I can get some of this working. I know you said some changes where coming. Would the changes impact work done here?

**Comment by regisb** [comment]
This issue has not received any attention for a long time. I don't really see a clear way forward, so I'm going to close this. Feel free to re-open or comment if you have fresh ideas.
