### ISSUE TITLE
502 Bad Gateway nginx

### ISSUE THREAD

**Issue by adesrod** [regisb/tutor#132]
Hello, I have the next problem with the platform " 502 Bad Gateway nginx", when I look the server I found that eight of seventeen dockers always are restarting. 

1. first of all, the current version is: 
 with the command "git log -1"

* commit c2d536dae5102e5ace24d0d8432ba8b5165c46ca
Author: R<C3><A9>gis Behmo <regis@behmo.com>
Date:   Tue Oct 2 08:36:29 2018 +0200

2. with the command  "make info"
* uname -a
Linux ip-172-31-77-84 4.4.0-1065-aws #75-Ubuntu SMP Fri Aug 10 11:14:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
git rev-parse HEAD
c2d536dae5102e5ace24d0d8432ba8b5165c46ca
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
docker-compose --version
docker-compose version 1.18.0, build 8dd22a9

3. with the command " ~/openedx-docker$ docker ps"

* CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                                  PORTS                                      NAMES
178fbcb900ab        regis/openedx:hawthorn          "docker-entrypoint..."   15 minutes ago      Restarting (1) 7 seconds ago                                                       openedxdocker_lms_worker_1
7f7d9c4493f9        regis/openedx:hawthorn          "docker-entrypoint..."   15 minutes ago      Restarting (1) 8 seconds ago                                                       openedxdocker_cms_worker_1
d2d687d4d67a        regis/openedx:hawthorn          "docker-entrypoint..."   15 minutes ago      Restarting (3) Less than a second ago                                              openedxdocker_lms_1
a73821f3aa86        regis/openedx:hawthorn          "docker-entrypoint..."   15 minutes ago      Restarting (3) 59 seconds ago                                                      openedxdocker_cms_1
f2f906e4c929        regis/openedx-xqueue:hawthorn   "./manage.py run_c..."   15 minutes ago      Restarting (1) 23 seconds ago                                                      openedxdocker_xqueue_consumer_1
56963dd01c75        regis/openedx-notes:hawthorn    "/bin/sh -c 'gunic..."   15 minutes ago      Restarting (3) 19 seconds ago                                                      openedxdocker_notes_1
8bbb5ddf5042        regis/openedx-xqueue:hawthorn   "/bin/sh -c 'gunic..."   15 minutes ago      Restarting (3) 13 seconds ago                                                      openedxdocker_xqueue_1
cb7e748f1ed6        regis/openedx-forum:hawthorn    "/bin/sh -c './bin..."   15 minutes ago      Up 15 minutes                           4567/tcp                                   openedxdocker_forum_1
bd067bfe8ac8        portainer/portainer:latest      "/portainer"             15 minutes ago      Up 15 minutes                           9000/tcp                                   openedxdocker_portainer_1
83447df25fe0        rabbitmq:3.6.10                 "docker-entrypoint..."   15 minutes ago      Up 15 minutes                           4369/tcp, 5671-5672/tcp, 25672/tcp         openedxdocker_rabbitmq_1
9ed1123a00a7        namshi/smtp                     "/bin/entrypoint.s..."   15 minutes ago      Up 15 minutes                           25/tcp                                     openedxdocker_smtp_1
3e12da843555        mongo:3.2.16                    "docker-entrypoint..."   15 minutes ago      Up 15 minutes                           27017/tcp                                  openedxdocker_mongodb_1
64b574c89bfc        mysql:5.6.36                    "docker-entrypoint..."   15 minutes ago      Up 15 minutes                           3306/tcp                                   openedxdocker_mysql_1
e7dc528afcac        memcached:1.4.38                "docker-entrypoint..."   15 minutes ago      Up 15 minutes                           11211/tcp                                  openedxdocker_memcached_1
c01523b4c357        nginx:1.13                      "nginx -g 'daemon ..."   15 minutes ago      Up 15 minutes                           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   openedxdocker_nginx_1
a3abde898790        elasticsearch:1.5.2             "/docker-entrypoin..."   15 minutes ago      Up 15 minutes                           9200/tcp, 9300/tcp                         openedxdocker_elasticsearch_1

4. with the command " docker logs openedxdocker_lms_worker_1 " : 

* Traceback (most recent call last):
  File "/openedx/edx-platform/manage.py", line 117, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named production
Traceback (most recent call last):
  File "/openedx/edx-platform/manage.py", line 117, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
5.  I already read an issue similar for " No module named production" and  following: make cms on the host, and then in the container give the result of all following commands:
ls -lh cms/envs/universal
ls -lh cms/envs/universal/
ls -lh /openedx/config/
ls -lh /openedx/config/universal/cms/ 

* with the command "make cms"
docker-compose -f docker-compose.yml -f docker-compose-xqueue.yml -f docker-compose-notes.yml -f docker-compose-portainer.yml run --rm -e USERID=$(id -u) -e SETTINGS=universal.production -p 8001:8001 cms bash
Starting openedxdocker_smtp_1 ...
Starting openedxdocker_mysql_1 ...
Starting openedxdocker_rabbitmq_1 ...
Starting openedxdocker_memcached_1 ... done
Starting openedxdocker_mongodb_1 ... done
creating new user 'openedx' with UID 1000
* with the command  "ls -lh cms/envs/universal"
ls: cannot access 'cms/envs/universal': No such file or directory
* with the command  "l ls -lh cms/envs/universal/"
ls: cannot access 'cms/envs/universal/': No such file or directory
* with the command  "l ls -lh /openedx/config/"
total 32K
-rw-rw-r-- 1 openedx openedx  817 Jan 15 13:01 cms.auth.json
-rw-rw-r-- 1 openedx openedx 2.7K Jan 15 13:01 cms.env.json
-rw-rw-r-- 1 openedx openedx  817 Jan 15 13:01 lms.auth.json
-rw-rw-r-- 1 openedx openedx 3.1K Jan 15 13:01 lms.env.json
-rwxrwxr-x 1 openedx openedx  423 Jan 15 13:01 oauth2.sh
-rwxrwxr-x 1 openedx openedx  851 Jan 15 13:01 provision.sh
-rwxrwxr-x 1 openedx openedx  346 Jan 15 13:01 stats
drwxr-xr-x 4 openedx openedx 4.0K Oct  1 18:14 universal
* with the command  "l ls -lh /openedx/config/universal/cms/"
total 16K
-rw-rw-r-- 1 openedx openedx    0 Jan 15 13:01 __init__.py
-rw-r--r-- 1 openedx root     139 Oct  1 21:35 __init__.pyc
-rw-rw-r-- 1 openedx openedx  644 Jan 15 13:01 development.py
-rw-rw-r-- 1 openedx openedx  890 Jan 15 13:01 production.py
-rw-r--r-- 1 openedx root    1.1K Oct  1 21:35 production.pyc

6. I appreciate any idea or possible solution

**Comment by regisb** [comment]
Hi @adesrod! You are running on an older version of Tutor. Can you please try to stop all containers and upgrade, as per http://docs.tutor.overhang.io/en/latest/local.html#how-to-upgrade-from-openedx-docker ?

**Comment by regisb** [comment]
This is surprising. Can you try to run `make stop` and then `make all` in the deploy/local folder?

**Comment by adesrod** [comment]
hello...  I  try  "make stop" and then  I compress  all folder "docker-compose" and I copy to another server  and next  try to run  "make all" in the deploy/local folder and here the result 
make all
Unable to find image 'regis/openedx-configurator:hawthorn' locally
hawthorn: Pulling from regis/openedx-configurator
cd784148e348: Pull complete
a5ca736b15eb: Pull complete
4a98ed320893: Pull complete
7b49c8b5b952: Pull complete
4a3c25efc1ef: Pull complete
c21df7563729: Pull complete
691788fdd100: Pull complete
b3c21482ee7f: Pull complete
7edcbdc352ec: Pull complete
Digest: sha256:2e220eab5052cf567ca13313a6fb7c7047ce53e27e28547613f0bf5ce30c094b
Status: Downloaded newer image for regis/openedx-configurator:hawthorn
ERROR Missing config value ''LANGUAGE_CODE' is undefined' for template /openedx/templates/openedx/config/lms.env.json
Makefile:20: recipe for target 'substitute' failed
make[2]: *** [substitute] Error 1
Makefile:5: recipe for target 'env' failed
make[1]: *** [env] Error 2
Makefile:53: recipe for target 'env' failed
make: *** [env] Error 2

**Comment by regisb** [comment]
@adesrod this is a different issue. Does that mean you managed to solve the 502 error mentioned in the title of this issue?

FYI, if you want to run the same platform on a different server, you need to sync the entire `tutor` folder.

**Comment by regisb** [comment]
@adesrod please paste here the result of `make info`.

**Comment by regisb** [comment]
The mysql issue you have now is unrelated to the initial issue, so I am going to close this now. I believe you have the same issue as #133, for which I just introduced a fix. Please delete your database, upgrade and start again:

```
make stop
sudo rm -rf ../../data/mysql
git pull
make all
```
