### ISSUE TITLE
Newbie help again

### ISSUE THREAD

**Issue by roblhibbard** [regisb/tutor#133]
I decided to start from scratch on a testbox and all was going well until I decided to remove all volumes, containers and such.

I removed the tutor directory also.

Started with the quick start and get an error stating:

Host '172.18.0.1' is not allowed to connect to this MySQL.

any suggestions.

thank you,

Robert H

**Comment by regisb** [comment]
Hi @roblhibbard! Did you make sure all containers were stopped (with `docker stop`) prior to restarting the platform?

**Comment by roblhibbard** [comment]
I think I did, but it could be a possibility I did not

**Comment by roblhibbard** [comment]
Output of Make stop

robert@hibbsedx:~/tutor/deploy/local$ make stop

docker-compose rm --stop --force

Stopping local_forum_1 ... done

Going to remove local_nginx_1, local_lms_worker_1, local_cms_worker_1, local_lms_1, local_cms_1, local_forum_1, local_notes_1, local_memcached_1, local_openedx-assets_1, local_rabbitmq_1, local_elasticsearch_1, local_mongodb_1, local_smtp_1, local_mysql_1

Removing local_nginx_1          ... done

Removing local_lms_worker_1     ... done

Removing local_cms_worker_1     ... done

Removing local_lms_1            ... done

Removing local_cms_1            ... done

Removing local_forum_1          ... done

Removing local_notes_1          ... done

Removing local_memcached_1      ... done

Removing local_openedx-assets_1 ... done

Removing local_rabbitmq_1       ... done

Removing local_elasticsearch_1  ... done

Removing local_mongodb_1        ... done

Removing local_smtp_1           ... done

Removing local_mysql_1          ... done

robert@hibbsedx:~/tutor/deploy/local$

 

Output of docker ps

robert@hibbsedx:~/tutor/deploy/local$ docker ps

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

robert@hibbsedx:~/tutor/deploy/local$

 

output of make all

 

robert@hibbsedx:~/tutor/deploy/local$ make all

Unable to find image 'regis/openedx-configurator:hawthorn' locally

hawthorn: Pulling from regis/openedx-configurator

cd784148e348: Pull complete

a5ca736b15eb: Pull complete

4a98ed320893: Pull complete

7b49c8b5b952: Pull complete

4a3c25efc1ef: Pull complete

c21df7563729: Pull complete

691788fdd100: Pull complete

b3c21482ee7f: Pull complete

7edcbdc352ec: Pull complete

Digest: sha256:2e220eab5052cf567ca13313a6fb7c7047ce53e27e28547613f0bf5ce30c094b

Status: Downloaded newer image for regis/openedx-configurator:hawthorn

make[1]: Entering directory '/home/robert/tutor/deploy/local'

make[1]: Leaving directory '/home/robert/tutor/deploy/local'

make[1]: Entering directory '/home/robert/tutor/deploy/local'

make[1]: Leaving directory '/home/robert/tutor/deploy/local'

make[1]: Entering directory '/home/robert/tutor/deploy/local'

docker-compose pull

Pulling memcached      ... done

Pulling mongodb        ... done

Pulling mysql          ... done

Pulling elasticsearch  ... done

Pulling openedx-assets ... done

Pulling rabbitmq       ... done

Pulling smtp           ... done

Pulling forum          ... done

Pulling lms            ... done

Pulling cms            ... done

Pulling lms_worker     ... done

Pulling cms_worker     ... done

Pulling notes          ... done

Pulling nginx          ... done

make[1]: Leaving directory '/home/robert/tutor/deploy/local'

make[1]: Entering directory '/home/robert/tutor/deploy/local'

docker-compose up -d mysql

Creating local_mysql_1 ... done

docker-compose stop mysql

Stopping local_mysql_1 ... done

docker-compose run --rm -v $(pwd)/../env/openedx/scripts:/openedx/scripts lms /openedx/scripts/provision.sh

Creating local_memcached_1     ... done

Starting local_mysql_1         ... done

Creating local_rabbitmq_1      ... done

Creating local_smtp_1          ... done

Creating local_elasticsearch_1 ... done

Creating local_mongodb_1       ... done

Creating local_forum_1         ... done

2019/01/22 13:22:03 Waiting for: tcp://mysql:3306

2019/01/22 13:22:03 Connected to tcp://mysql:3306

mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1130 (HY000): Host '172.18.0.9' is not allowed to connect to this MySQL server

Waiting for mysql database to be ready...

mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1130 (HY000): Host '172.18.0.9' is not allowed to connect to this MySQL server

Waiting for mysql database to be ready...

mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1130 (HY000): Host '172.18.0.9' is not allowed to connect to this MySQL server

Waiting for mysql database to be ready...

mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 1130 (HY000): Host '172.18.0.9' is not allowed to connect to this MySQL server

 

Maybe this will make sense to you.

 

Again thank you for taking a look at this.

 

Robert

**Comment by regisb** [comment]
This is really strange. Let's start from a blank slate:

```
make stop
sudo rm -rf ../../data/mysql
make configure
make all
```

**Comment by isabyr** [comment]
Same problem here, workaround is to connect to mysql and grant access explicitly:
```
docker exec -it local_mysql_1 /bin/sh
mysql
use mysql;
GRANT ALL PRIVILEGES ON *.* TO root@that_ip IDENTIFIED BY 'pass in mysql/auth.env' WITH GRANT OPTION;
```
then just re-run the last command

**Comment by regisb** [comment]
@isabyr did you try my proposed fix https://github.com/regisb/tutor/issues/133#issuecomment-456412751 ?

**Comment by regisb** [comment]
You should have pretty much the same configuration: 

```
$ docker network inspect local_default
[
    {
        "Name": "local_default",
        "Id": "105ad87e65d9c477f473281d9c143346a1a59660655d94a16e7cf58ca33f41e9",
        "Created": "2018-12-03T19:15:13.499013114+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.22.0.0/16",
                    "Gateway": "172.22.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "17686b9e293aa21c4a060989861513cd1fc65653dd824ce6dd6024af4a6157b3": {
                "Name": "local_mongodb_1",
                "EndpointID": "d9b2b90618a8fe40bff1e9636c72bd96169078cd3210b308b0fedd32bc66bc36",
                "MacAddress": "02:42:ac:16:00:04",
                "IPv4Address": "172.22.0.4/16",
                "IPv6Address": ""
            },
            "19444f38c005bfffc488c8f0b52886b9294f109c16a9a9065e565cfa06b6634e": {
                "Name": "local_elasticsearch_1",
                "EndpointID": "7a1d8c7b51a8f81a9cd62a09fb694d62586ade8164fc11ac756c09ab235578fc",
                "MacAddress": "02:42:ac:16:00:07",
                "IPv4Address": "172.22.0.7/16",
                "IPv6Address": ""
            },
            "4b02afe08ff25a5fb9278c9cba39d23a21d331496793d83bcf2b3e0658e0ef61": {
                "Name": "local_mysql_1",
                "EndpointID": "30ffefd52d6e9b132d324f1e44bedfcdd74cdfa8bd1565e47217ee814b9b30a6",
                "MacAddress": "02:42:ac:16:00:05",
                "IPv4Address": "172.22.0.5/16",
                "IPv6Address": ""
            },
            "52d9198bddae2abdb5f8e564454a274e365b7cb6632f85c2eac13e142e629c6f": {
                "Name": "local_memcached_1",
                "EndpointID": "2cccba4cff1cfe5589b7b04cb23cb09d4e401f0c51581d8dec991fbdb2c22521",
                "MacAddress": "02:42:ac:16:00:02",
                "IPv4Address": "172.22.0.2/16",
                "IPv6Address": ""
            },
            "5d0a443053a8efb4777dfe7455182245ab593cef34c934989d1f57274703168d": {
                "Name": "local_lms_1",
                "EndpointID": "bf40c0282a973323502d685bed2d8f9c5860380de760ce0b5e67ed7bdceeae4c",
                "MacAddress": "02:42:ac:16:00:0c",
                "IPv4Address": "172.22.0.12/16",
                "IPv6Address": ""
            },
            "7c8f66a5bc08f4fa095ccaaa563eef1e84eb0879e58a3507f819f84aee5061e5": {
                "Name": "local_rabbitmq_1",
                "EndpointID": "e2c2a04759a07b201b02373fe3a7f3279622a4223bc8ba796c00a336607d51d7",
                "MacAddress": "02:42:ac:16:00:08",
                "IPv4Address": "172.22.0.8/16",
                "IPv6Address": ""
            },
            "ac3bb0ba8e59c79a03aab3cfe0285bce73f1f647666b22739d6689c4c0f5cd33": {
                "Name": "local_nginx_1",
                "EndpointID": "3399efbd202cb0984a0b4e5104f7084c2c733a41d87fb7dc1161e2ef45d94583",
                "MacAddress": "02:42:ac:16:00:0d",
                "IPv4Address": "172.22.0.13/16",
                "IPv6Address": ""
            },
            "cd4e6ac49e9dbd14f5ca06d6559bb555d4675f467ed4cd81126b5594d72d112d": {
                "Name": "local_smtp_1",
                "EndpointID": "c48d9d25daa2552401697a96ea08d5fd16232c64122b4489b859e90170dd487f",
                "MacAddress": "02:42:ac:16:00:06",
                "IPv4Address": "172.22.0.6/16",
                "IPv6Address": ""
            },
            "da1eeefd3803405ecd8f12cb715777dbe290417e84f804f94b193caf9bc102b9": {
                "Name": "local_lms_worker_1",
                "EndpointID": "e51083777fda5a62fe7c118f87bf7ff9f5977002655a62b7541a9292f53acdc6",
                "MacAddress": "02:42:ac:16:00:0e",
                "IPv4Address": "172.22.0.14/16",
                "IPv6Address": ""
            },
            "de86874ca807aefa9491250d7cd4055b34a210fcb6acccb0fbbb461a00b14c74": {
                "Name": "local_cms_1",
                "EndpointID": "e24d5969720617eaeb00ea32e52b8ad39181d5d955655f6438dd4e54e04ed22e",
                "MacAddress": "02:42:ac:16:00:09",
                "IPv4Address": "172.22.0.9/16",
                "IPv6Address": ""
            },
            "e305a68d7b3c41644cc4d09017de23b24cce123675909e4bc1b711eb4a6de24f": {
                "Name": "local_cms_worker_1",
                "EndpointID": "828063aa8f6cbf57278c687c35e2ab74ca0bedb854216a0e3fc54c93ff602ce5",
                "MacAddress": "02:42:ac:16:00:0a",
                "IPv4Address": "172.22.0.10/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "local",
            "com.docker.compose.version": "1.21.2"
        }
    }
]
```

**Comment by regisb** [comment]
You should have pretty much the same configuration: 

```
$ docker network inspect local_default
[
    {
        "Name": "local_default",
        "Id": "105ad87e65d9c477f473281d9c143346a1a59660655d94a16e7cf58ca33f41e9",
        "Created": "2018-12-03T19:15:13.499013114+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.22.0.0/16",
                    "Gateway": "172.22.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "17686b9e293aa21c4a060989861513cd1fc65653dd824ce6dd6024af4a6157b3": {
                "Name": "local_mongodb_1",
                "EndpointID": "d9b2b90618a8fe40bff1e9636c72bd96169078cd3210b308b0fedd32bc66bc36",
                "MacAddress": "02:42:ac:16:00:04",
                "IPv4Address": "172.22.0.4/16",
                "IPv6Address": ""
            },
            "19444f38c005bfffc488c8f0b52886b9294f109c16a9a9065e565cfa06b6634e": {
                "Name": "local_elasticsearch_1",
                "EndpointID": "7a1d8c7b51a8f81a9cd62a09fb694d62586ade8164fc11ac756c09ab235578fc",
                "MacAddress": "02:42:ac:16:00:07",
                "IPv4Address": "172.22.0.7/16",
                "IPv6Address": ""
            },
            "4b02afe08ff25a5fb9278c9cba39d23a21d331496793d83bcf2b3e0658e0ef61": {
                "Name": "local_mysql_1",
                "EndpointID": "30ffefd52d6e9b132d324f1e44bedfcdd74cdfa8bd1565e47217ee814b9b30a6",
                "MacAddress": "02:42:ac:16:00:05",
                "IPv4Address": "172.22.0.5/16",
                "IPv6Address": ""
            },
            "52d9198bddae2abdb5f8e564454a274e365b7cb6632f85c2eac13e142e629c6f": {
                "Name": "local_memcached_1",
                "EndpointID": "2cccba4cff1cfe5589b7b04cb23cb09d4e401f0c51581d8dec991fbdb2c22521",
                "MacAddress": "02:42:ac:16:00:02",
                "IPv4Address": "172.22.0.2/16",
                "IPv6Address": ""
            },
            "5d0a443053a8efb4777dfe7455182245ab593cef34c934989d1f57274703168d": {
                "Name": "local_lms_1",
                "EndpointID": "bf40c0282a973323502d685bed2d8f9c5860380de760ce0b5e67ed7bdceeae4c",
                "MacAddress": "02:42:ac:16:00:0c",
                "IPv4Address": "172.22.0.12/16",
                "IPv6Address": ""
            },
            "7c8f66a5bc08f4fa095ccaaa563eef1e84eb0879e58a3507f819f84aee5061e5": {
                "Name": "local_rabbitmq_1",
                "EndpointID": "e2c2a04759a07b201b02373fe3a7f3279622a4223bc8ba796c00a336607d51d7",
                "MacAddress": "02:42:ac:16:00:08",
                "IPv4Address": "172.22.0.8/16",
                "IPv6Address": ""
            },
            "ac3bb0ba8e59c79a03aab3cfe0285bce73f1f647666b22739d6689c4c0f5cd33": {
                "Name": "local_nginx_1",
                "EndpointID": "3399efbd202cb0984a0b4e5104f7084c2c733a41d87fb7dc1161e2ef45d94583",
                "MacAddress": "02:42:ac:16:00:0d",
                "IPv4Address": "172.22.0.13/16",
                "IPv6Address": ""
            },
            "cd4e6ac49e9dbd14f5ca06d6559bb555d4675f467ed4cd81126b5594d72d112d": {
                "Name": "local_smtp_1",
                "EndpointID": "c48d9d25daa2552401697a96ea08d5fd16232c64122b4489b859e90170dd487f",
                "MacAddress": "02:42:ac:16:00:06",
                "IPv4Address": "172.22.0.6/16",
                "IPv6Address": ""
            },
            "da1eeefd3803405ecd8f12cb715777dbe290417e84f804f94b193caf9bc102b9": {
                "Name": "local_lms_worker_1",
                "EndpointID": "e51083777fda5a62fe7c118f87bf7ff9f5977002655a62b7541a9292f53acdc6",
                "MacAddress": "02:42:ac:16:00:0e",
                "IPv4Address": "172.22.0.14/16",
                "IPv6Address": ""
            },
            "de86874ca807aefa9491250d7cd4055b34a210fcb6acccb0fbbb461a00b14c74": {
                "Name": "local_cms_1",
                "EndpointID": "e24d5969720617eaeb00ea32e52b8ad39181d5d955655f6438dd4e54e04ed22e",
                "MacAddress": "02:42:ac:16:00:09",
                "IPv4Address": "172.22.0.9/16",
                "IPv6Address": ""
            },
            "e305a68d7b3c41644cc4d09017de23b24cce123675909e4bc1b711eb4a6de24f": {
                "Name": "local_cms_worker_1",
                "EndpointID": "828063aa8f6cbf57278c687c35e2ab74ca0bedb854216a0e3fc54c93ff602ce5",
                "MacAddress": "02:42:ac:16:00:0a",
                "IPv4Address": "172.22.0.10/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "local",
            "com.docker.compose.version": "1.21.2"
        }
    }
]
```

@roblhibbard can you please also paste the result of the `make info` command?

**Comment by roblhibbard** [comment]
I will have to get back with you later tonight, will be out for the next
3-4 hours

**Comment by roblhibbard** [comment]
rob@hibbsedxbox:~/tutor/deploy/local$ docker network inspect local_default

<pre>[

    {

        "Name": "local_default",

        "Id": "adb0640f1fd0025c0d52e375bb0cde4541eea0209a57b892deeca05293d19cb1",

        "Created": "2019-01-22T06:55:14.588270635-07:00",

        "Scope": "local",

        "Driver": "bridge",

        "EnableIPv6": false,

        "IPAM": {

            "Driver": "default",

            "Options": null,

            "Config": [

                {

                    "Subnet": "172.18.0.0/16",

                    "Gateway": "172.18.0.1"

                }

            ]

        },

        "Internal": false,

        "Attachable": true,

        "Ingress": false,

        "ConfigFrom": {

            "Network": ""

        },

        "ConfigOnly": false,

        "Containers": {

            "077fb71eae0cbe653b2ef757cf90437907dbe22b398497ee5a0083b0b6f8d86d": {

                "Name": "local_elasticsearch_1_81a254b950d3",

                "EndpointID": "a0feef85294ca54a80830b68ce70e291dbf244bf5ac73b8ac03462441e8a1535",

                "MacAddress": "02:42:ac:12:00:04",

                "IPv4Address": "172.18.0.4/16",

                "IPv6Address": ""

            },

            "19f604d6d556d7e9e29ce7ad9d29a01101ee2761d7f71efa1f64478bd710b8a6": {

                "Name": "local_smtp_1_30b0b029daec",

                "EndpointID": "3436a59ca34e5725318de0de2cc78f22a89fcc722b337c94e2a0396f950e8bcf",

                "MacAddress": "02:42:ac:12:00:03",

                "IPv4Address": "172.18.0.3/16",

                "IPv6Address": ""

            },

            "79b33538f9c8f11129e63749efe440add29fda4cd818a105cfc8186897f90969": {

                "Name": "local_mysql_1_c558848ef2ae",

                "EndpointID": "29db485661efd1a9d094ecab9cd8638a6c44e716099255ca9bb22778542f8846",

                "MacAddress": "02:42:ac:12:00:02",

                "IPv4Address": "172.18.0.2/16",

                "IPv6Address": ""

            },

            "845768407f22a623994a41f92f6b0beb73348272fb4035d9f9add6fe5ee95319": {

                "Name": "local_memcached_1_663dd38826d6",

                "EndpointID": "b8ca85565e79a561ada19b74e39a62bc1afaa938b4dd53884fba95268b244082",

                "MacAddress": "02:42:ac:12:00:05",

                "IPv4Address": "172.18.0.5/16",

                "IPv6Address": ""

            },

            "988563ef52955cc6c689e50a776e0d43bf487eae800d9ea66cf5849a497fbf86": {

                "Name": "local_rabbitmq_1_db3d11f1d304",

                "EndpointID": "37487c50f0090469d6bc24d9ba3f742e31540dc87c149f5ebb458650df97d348",

                "MacAddress": "02:42:ac:12:00:06",

                "IPv4Address": "172.18.0.6/16",

                "IPv6Address": ""

            },

            "f56b1f11c1d7616453b1dd1c48a2d1e372c768aef3112c9878a63a715df71dd1": {

                "Name": "local_mongodb_1_68cfa5444b2e",

                "EndpointID": "6e16ed6d5fc7a16abc0e14c7cc4c4104eef0e5d7ec811a9e5b15a829a66808f8",

                "MacAddress": "02:42:ac:12:00:07",

                "IPv4Address": "172.18.0.7/16",

                "IPv6Address": ""

            }

        },

        "Options": {},

        "Labels": {

            "com.docker.compose.network": "default",

            "com.docker.compose.project": "local",

            "com.docker.compose.version": "1.23.1"

        }

    }

]

 

make -s -C ../.. info

Linux hibbsedxbox 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

-------------------------

6d70dedce0b646a907f51f2f78457644ff751797

 

</pre>

-------------------------

Client:

Version:           18.09.1

API version:       1.39

Go version:        go1.10.6

Git commit:        4c52b90

Built:             Wed Jan  9 19:35:23 2019

OS/Arch:           linux/amd64

Experimental:      false

 

Server: Docker Engine - Community

Engine:

  Version:          18.09.1

  API version:      1.39 (minimum version 1.12)

  Go version:       go1.10.6

  Git commit:       4c52b90

  Built:            Wed Jan  9 19:02:44 2019

  OS/Arch:          linux/amd64

  Experimental:     false

-------------------------

docker-compose version 1.23.1, build b02f1306

-------------------------

**Comment by regisb** [comment]
@roblhibbard the lms and the cms do not appear in your `local_default` network. Is that because they did not launch?
What makes you say that your local_default network is "out of the ordinary"?

**Comment by regisb** [comment]
@roblhibbard I think I found a solution. This might be due to a change I introduced recently that tried to make sure mysql is initialized properly prior to creating the databases. Apparently, it's not working that well... Please try the following:

```
make stop
sudo rm -rf ../../data/mysql
git pull
make all
```

**Comment by roblhibbard** [comment]
I will give this a try now.

 

Thank you,

 

Robert

**Comment by roblhibbard** [comment]
Yeah,

 

Back up and running again,

 

Thank you,

 

Robert

**Comment by regisb** [comment]
Awesome! Pfiuh, that was hard.

**Comment by roblhibbard** [comment]
So now that my platform is working again, I was able to get the jupyter-edx-grader-xblock installed and working on my testbox. I ended up adding

run pip install --src ../venv/src -r IPython==5.0

run pip install --src ../venv/src -r ipykernel==4.10

 

to the openedx Dockerfile. This allowed for jupyter to be installed via the private.txt. I cloned the edx-platform and added the other items via the CMS and LMS.

 

Thanks again for all your help,

 

Robert

**Comment by regisb** [comment]
That's great news! FYI, you don't have to modify the Dockerfile. You just need to add your dependencies to your private requirements.

`private.txt`:

```
IPython==5.0 
ipykernel==4.10
git+https://github.com/ibleducation/jupyter-edx-grader-xblock.git
```

**Comment by regisb** [comment]
Indeed, this is not related to tutor at all. But I suspect the xblock requires docker, which is not available from inside the container... You would need to add `print cmd` to line 158 of /usr/local/lib/python2.7/dist-packages/xblock_jupyter_graded/container_manager.py to debug this.

When I quickly checked the documentation of xblock_jupyter_graded, I didn't realize that the xblock was itself running docker containers. It's possible to launch containers inside containers, but it's tricky.
