### ISSUE TITLE
theming question

### ISSUE THREAD

**Issue by JeffKatzy** [regisb/tutor#140]
## Steps to reproduce

* Go to  [tutor documentation on theming](http://docs.tutor.overhang.io/en/latest/customise.html)
* After running `make build-openedx`, says to follow the [edx documentation](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/enable_themes.html#apply-a-theme-to-a-site)
* Open edx docs talk about changing the lms.env.json file.  

That's where I'm unsure of what to do.

Do [these files](https://github.com/regisb/tutor/tree/master/deploy/templates/openedx/config) belong under `edx-platform/lms/envs/tutor/`?  Do they belong in `edx-platform/lms/envs/tutor/config/`?

Is there anything to do with [settings/lms/assets file](https://github.com/regisb/tutor/blob/master/build/openedx/settings/lms/assets.py)?

**Comment by JeffKatzy** [comment]
Ok, thanks for the clarification.  I think there were two things that confused me.  

1. Is that in the [linked edx docs](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/enable_themes.html#apply-a-theme-to-a-site), step 1 links you back to the enable and apply section. 

2. The other is that in the [tutor docs](http://docs.tutor.overhang.io/en/latest/customise.html), it says " Open edX documentation to enable your themes", -- maybe it should instead say to "apply".  It looks like enabling happens via the generation of *.env.json you described and can be skipped.

**Comment by regisb** [comment]
@JeffKatzy I'm closing this after I made some changes to the documentation that attempt to clarify theming.
