### ISSUE TITLE
Grade Download Needed

### ISSUE THREAD

**Issue by frohro** [regisb/tutor#143]
I have been using tutor with good results this school year in a blended learning environment.  I am getting to the point where I think the analytics package would be very nice to have.  The things I see as being really helpful are:

- Being able to download the grades.  Last quarter I had to compute the grades by hand, because I had some work outside open edX, and it seems I cannot download the open edX grades.  It might need the analytics package.  Here is what I see on the tutor open edX: 
![image](https://user-images.githubusercontent.com/994565/52160648-9768da00-266e-11e9-8817-a1553953238b.png) 
Here is what I see on edunext.co:
![image](https://user-images.githubusercontent.com/994565/52160863-bb79ea80-2671-11e9-9cf8-e7fc24d08949.png)
- Being able to see the learner engagement would be really helpful to know if my efforts are placed optimally.  Making videos takes me around five hours for a ten minute video.  Finding them on YouTube takes me around an hour for a ten minute video.  Other indications are that my students are not putting in as many hours in my classes as they are in others.  I would love to explore this.  This may be more difficult, as it seems to be part of the [edX Insights](https://edx.readthedocs.io/projects/edx-insights/en/latest/learners/Learner_Activity.html).  

Any advice would be welcome!

Thanks,
Rob

**Comment by regisb** [comment]
@frohro I agree that Insights would be a great addition. *However*, I estimate that integrating Insights into Tutor is going to take ~1 month work. This is the reason why I am looking for sponsors for this effort. (see issue #58)

However, I'm not quite sure the feature you need is related to Insights. From my understanding, all we need is to activate the `ENABLE_GRADE_DOWNLOADS` feature. Can you try to add `ENABLE_GRADE_DOWNLOADS: true` to the `FEATURES` entry in lms.env.json?

**Comment by frohro** [comment]
Thanks Regis!
I edited the file in these two locations, but didn't change the one in templaces, and wow!  I got the options I need for downloading grades!  See the screenshot below:
![image](https://user-images.githubusercontent.com/994565/52181376-f1b88680-27a5-11e9-9ed0-75fb8fa9be69.png)
Thank you so much!!

I have noticed that when I actually try to download the grades, it claims to be doing that, but the grades do not appear as they do on edunext.co.  Some things seem to work like downloading a csv of the certificates, but not the grades.  See this screenshot:
![image](https://user-images.githubusercontent.com/994565/52181690-ae601700-27a9-11e9-9060-18176728ea95.png)
I tried it on the same course with edunext.co and it claims to have finished, but there is no link at the bottom of the tutor edX, while there is in the edunext.co edX.

I'm only a professor, and not in control of any budgets or even with much if any influence with anyone who might have funding for a month's work, but if I did, I think being able to look at learner engagement would be worth it.  I'm planning to work on selling others here at the university on the open edX platform for blended learning.  The analytics features would really help with that, but if something miraculous happens, and I am able to sell it in such a way that there is actually some funding available, I'll let you know.  In the meantime, I am happy to help with testing the platform for you.  I'm going to have to rely on student self reporting of their engagement, and trying to encourage it with quizzes, homework, and making the best content I can.

Again, thanks for the grade download feature.  Hopefully I can figure out what is the problem with

**Comment by frohro** [comment]
I had a problem with issue #136.  I'm hoping it may be my problem with not actually being able to download the grades.  I noted that I need to modify all the below files, for the fix to not disappear, but it doesn't appear to have solved that issue.
Here are the files I modified:
/home/frohro/openedx-docker/deploy/env/openedx/lms.env.json
/home/frohro/openedx-docker/deploy/env/openedx/config/lms.env.json
/home/frohro/openedx-docker/deploy/templates/openedx/config/lms.env.json

Thanks,
Rob

**Comment by regisb** [comment]
Let's solve issue #148 before we consider adding this feature by default.
FYI, file ` /home/frohro/openedx-docker/deploy/env/openedx/lms.env.json` is now useless and can be safely deleted.

**Comment by frohro** [comment]
I was going to ask you if it was safe to address this again, and it looks like it is, but I'm not certain this issue is really fixed.  I am still seeing what the screenshot above shows.  (No link appears.)  In other words, it doesn't make the link I see on edunext.co in this screen shot.
![image](https://user-images.githubusercontent.com/994565/52369142-dac39f80-2a04-11e9-875d-88a24823a511.png)
Maybe I'm not waiting long enough, but it seems 15 minutes should be plenty of time for less than 20 students.
Thanks!
Rob

**Comment by regisb** [comment]
@frohro I think I may have found a way to solve this, but I'm currently working on more urgent issues. Is it ok if this waits a week or two?

**Comment by frohro** [comment]
Certainly!

Rob

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by guilleironhack** [comment]
I'm experiencing the same issue when trying to generate and download reports. In other order of things, I would also love to see analytics/insights in tutor!

**Comment by regisb** [comment]
@guilleironhack thanks for your feedback! Are you or your company willing to sponsor the development effort

**Comment by guilleironhack** [comment]
@regisb I would love to, but I currently don't have enough know-how or effort available to do this having in mind that, as you mentioned, analytics/insights is not precisely simple

**Comment by regisb** [comment]
I meant "sponsor" in the sense of "financial support" :smiley: :moneybag: 
Let me ask this another way: how much would you or your company be willing to pay to add support for Insights?

**Comment by guilleironhack** [comment]
Hahaha now I get it! We would love to be able to do it, but I'm afraid we're not there yet. I might be able to contribute with some human effort, but again, lacking a bit of knowledge here.

**Comment by frohro** [comment]
Hi Regis,
Any chance you could look at this?  I'm at the end of the term, and it would be really nice to export the data from edx, rather than typing it all into a spread sheet or something.
Thanks,
Rob

**Comment by regisb** [comment]
Hi @frohro,
It was harder than I thought, but I think I managed to solve this issue. The feature will be present in release 3.2.1., which should become available in a couple minutes.

**Comment by frohro** [comment]
Thanks Regis!
I'm going to try upgrading again to tutor.  Last attempt did not work, as detailed in the overhang.io discussion, and I also copied my problems to issue 155.
Again, thanks for fixing this.  It makes doing a blended learning thing much much easier.  
Rob
