### ISSUE TITLE
Improve custom settings

### ISSUE THREAD

**Issue by tonytan4ever** [regisb/tutor#150]
When I try to include 

`from development import *  `

in my customized settings, I will get 

> ValueError: Attempted relative import in non-package

This will improve that: https://github.com/regisb/tutor/pull/149

**Comment by regisb** [comment]
Hi @tonytan4ever! Thanks for taking the time to open this issue and PR. I think it's a relevant feature, but I just need to better understand what you are trying to do. I'm a bit confused by the fact that you wrote `from development import *`, and not `from .development import *`. In the former case, I don't quite understand why you would get a "relative import" error.

In fact, you are creating your own settings module, right? Something like `mysettings.py` in which there is `from .development import *`?

**Comment by tonytan4ever** [comment]
A while ago I was encountering relative imporat error as development.py has this in it:

` from ..devstack import *`

However, this error seems gone as of latest tutor release.  I will close this issue.
I still think full path importing like 

`from lms.envs.devstack import *` is a better practice though.

**Comment by regisb** [comment]
> from lms.envs.devstack import * is a better practice though.

I think you're right :) let's discuss this further on your pr

**Comment by tonytan4ever** [comment]
Yes sir.  Looks like you have big big rewrite yesterday, so I had to close and re-open a new PR here:

https://github.com/regisb/tutor/pull/157
