### ISSUE TITLE
Need upgrade instructions for tutor-linux.... from old make setup

### ISSUE THREAD

**Issue by frohro** [regisb/tutor#155]
Since I was having trouble with my certificate, I thought maybe I should make stop, git pull, and make daemon.  There were a lot of changes, and now I find there is a new tutor-linux binary I need to run.  I'm a little afraid to just run it with quickstart for fear it will mess up my present installation.  In the meantime, I'm going back in time, until I can find some instructions on migration.

:-)
Thanks,
Rob

**Comment by regisb** [comment]
Hi Rob! Did you try http://docs.tutor.overhang.io/en/latest/local.html#upgrading-from-earlier-versions?

**Comment by regisb** [comment]
Hey @frohro! Did you manage to upgrade your install? If not, feel free to re-open this.

**Comment by frohro** [comment]
Hi Regis,
I'm finally getting brave enough to upgrade.  I reverted to the makefile version.  I found your link above does not work anymore, but it appears to be [here](https://docs.tutor.overhang.io/local.html?highlight=upgrade%20from%20earlier%20versions) instead.  I need to figure out how to pull the latest using git now, but I note as I read the instructions that it appears your instructions assume you have tutor in your path to create directories and move the data.  Then it says make sure tutor is in your path.  It isn't clear to me what directory I should be in (if it matters) to do the upgrade either.  

I'd like to try out your Android break through.  I think my students would use it, though just using Chrome seems to work pretty well too.
Thanks for all the help!
Rob

**Comment by regisb** [comment]
Hey @frohro! Indeed, in the switch to Tutor v3, I moved from a `make`-based install to a single binary. You should *not* run `git pull`. Instead, this is how you should install tutor now: https://docs.tutor.overhang.io/install.html#direct-binary-downloads

```
sudo curl -L "https://github.com/regisb/tutor/releases/download/latest/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
sudo chmod +x /usr/local/bin/tutor
```

You can then follow the instructions from https://docs.tutor.overhang.io/local.html#upgrading-from-earlier-versions

You probably want to make a backup of your install prior to upgrading. You can do so with:

```
mkdir ~/tutor-backup
cp -r config.json data/ ~/tutor-backup/
```

**Comment by regisb** [comment]
Feel free to open a topic on the discussion forums to discuss this further: https://discuss.overhang.io/

**Comment by frohro** [comment]
Hi Regis,

I put the following on the overhang.io as you suggested a while back, but as far as I can tell, I got no answers, so I'm posting it here.  I'm going to try again tonight or tomorrow morning.  
Thanks,
Rob

> I’m working on upgrading from makefile to tutor. Here is a summary of where I am on this:
> 
> Here are notes that might help Regis improve the instructions:
> 
> I suspect it might be best to make stop before backing up, but that wasn’t mentioned.
> 
> I noticed I had to sudo to do the cp -r to backup.
> 
> It wasn’t totally clear if it mattered where I was when I did tutor local quickstart. It seemed to work from my original openedx directory. I like all those green OK’s going by.  :wink:
> 
> Unfortunately I had a problem with the certificates. See below:
> 
> Databases ready.
> HTTPS certificates generation
> docker run --rm -it --volume /home/frohro/.local/share/tutor/data/letsencrypt:/etc/letsencrypt/ -p 80:80 --entrypoint=sh certbot/certbot:latest -c certbot certonly --standalone -n --agree-tos -m admin@edx.fweb.wallawalla.edu -d edx.fweb.wallawalla.edu -d studio.edx.fweb.wallawalla.edu -d preview.edx.fweb.wallawalla.edu
> 
> certbot certonly --standalone -n --agree-tos -m admin@edx.fweb.wallawalla.edu -d notes.edx.fweb.wallawalla.edu
> 
> docker: Error response from daemon: driver failed programming external connectivity on endpoint gallant_brattain (69fbf58008ed2b6d421af3a2207a24e31b82053bc1ecb201f5e53fd558f2af37): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.
> Error: Command failed with status 125: docker run --rm -it --volume /home/frohro/.local/share/tutor/data/letsencrypt:/etc/letsencrypt/ -p 80:80 --entrypoint=sh certbot/certbot:latest -c certbot certonly --standalone -n --agree-tos -m admin@edx.fweb.wallawalla.edu -d edx.fweb.wallawalla.edu -d studio.edx.fweb.wallawalla.edu -d preview.edx.fweb.wallawalla.edu
> 
> certbot certonly --standalone -n --agree-tos -m admin@edx.fweb.wallawalla.edu -d notes.edx.fweb.wallawalla.edu
> 
> frohro@fweb:~/openedx-docker$
> 
> So I stopped apache2, which was a tip from tony-h when I needed to renew certificates, and ran tutor local quickstart again.
> 
> Now I think it is up!
> 
> However, I can’t sign in yet. I’ll go read the docs.
> 
> I did tutor local createuser --staff --superuser yourusername user@email.com with my credentials, but all my classes are gone, and I suspect all my students are lost too.
> 
> I tried reindexing the courses, with no effect.
> 
> Then I decided this was not likely something I’ll fix in a minute or two so I went to restart my old makefile setup. It reminded me I had not restarted apache2, so I did that and it is back up and running at the moment, so all is well.
> 
> It would be nice to finish the upgrade though.
> 
> I’m tempted to make stop the old one, and do ttutor local start --detach, again now that apache2 is up, but I really don’t know what I’m doing, and don’t want to mess things up.
> 
> Any ideas?
> 
> Thanks,
> 
> Rob

**Comment by regisb** [comment]
Hey @frohro,
I had notification issues on the discuss.overhang.io mail server (https://discuss.overhang.io/t/mail-server-issue-please-do-no-flag-as-spam/20), so I missed your post. Btw, please do not flag the 250 emails as spam! :pray: 
I answered on the forums. Let's move the conversation there.
