### ISSUE TITLE
`tutor local env` raises "Host 'xxx' is not allowed to connect to this MySQL server"

### ISSUE THREAD

**Issue by roblhibbard** [regisb/tutor#159]
Hello Regis:

I really like the format for the new tutor. I am trying it out on a test machine before upgrading my old one. But running into a few issues.

When I run tutor local env nothing but the docker-compose.yml is copied over.

so when running tutor --version I get this error:

```
Traceback (most recent call last):
  File "main", line 4, in <module>
  File "tutor/cli.py", line 21, in main
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 716, in main
  File "site-packages/click/core.py", line 641, in make_context
  File "site-packages/click/core.py", line 1089, in parse_args
  File "site-packages/click/core.py", line 940, in parse_args
  File "site-packages/click/core.py", line 1477, in handle_parse_result
  File "site-packages/click/core.py", line 96, in invoke_param_callback
  File "site-packages/click/decorators.py", line 270, in callback
RuntimeError: Could not determine version
[9883] Failed to execute script main
```

and when I have tried running the tutor local quickstart, I run into this error.

```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.9' is not allowed to connect to this MySQL server
```

I downloaded the binary and uploaded it to /home/robert/bin:

```
echo $PATH
/home/robert/bin:/home/robert/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

I then used the chmod +x tutor command to make it executable 

and most of the commands work accept tutor --help and tutor web ui --help

Not sure what is happening?

any insight would be awesome. 

I am running the latest Ubuntu 18.04 server.

thank you,

Robert

**Comment by regisb** [comment]
Hi Robbert!
Indeed, the `--version` issue was also reported in issue #156, and it's going to be fixed soon.

However, the mysql issue is more troubling. Did you remember to stop containers (with `make stop`) prior to upgrading? You can verify with `docker ps`.

**Comment by roblhibbard** [comment]
hello,

this is a fresh install of ubuntu server, no upgrade needed, I am just testing this one before using on my working install. So I am just using the tutor local quickstart

should there be anything in the ~/.local/share/tutor/env/local file besides the docker-compose.yml?

thanks,

Robert

**Comment by roblhibbard** [comment]
Hello,
I thought I would send the other part of the error. 

Error: Command failed with status 1: docker-compose -f /home/robert/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s

mysql -u root --password="hcEsJQhx" --host "mysql" -e 'CREATE DATABASE IF NOT EXISTS openedx;'
mysql -u root --password="hcEsJQhx" --host "mysql" -e 'GRANT ALL ON openedx.* TO "openedx"@"%" IDENTIFIED BY "hcEsJQhx";'

**Comment by regisb** [comment]
This should be solved by https://github.com/regisb/tutor/commit/9ce68aa3139500f69e3b513cb5a6eb428c1bb9d2 in v3.0.1.
