### ISSUE TITLE
custom authentication - modifying lms.auth.json without local development

### ISSUE THREAD

**Issue by JeffKatzy** [regisb/tutor#163]
## Steps to reproduce

I am trying to use a custom authentication with edx, via use of either Auth0.  Looking at the [open edx docs](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/tpa/tpa_integrate_open/tpa_oauth.html), I need to both alter the `lms.env.json` file and then the `lms.auth.json` file.

I am trying to avoid doing any local development of open edx, but instead simply modify the files in the `tutor` repo.

It appears that I can make a change in the `lms.env.json` file via the [`assets.py`](https://github.com/regisb/tutor/blob/master/tutor/templates/build/openedx/settings/lms/assets.py) file in tutor.  But how do I alter the `lms.auth.json` file via tutor?

**Comment by regisb** [comment]
@JeffKatzy Both `*.env.json` and `*.auth.json` files need to be modified from the `tutor/templates` folder: https://github.com/regisb/tutor/tree/master/tutor/templates/apps/openedx/config

**Comment by JeffKatzy** [comment]
awesome - thank you!
