### ISSUE TITLE
LMS fails in kubernetes, Forum Fails

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#166]
## Steps to reproduce
`tutor k8s quickstart`
`kubectl --namespace openedx logs lms-7547c6d659-d4lc8`

![image](https://user-images.githubusercontent.com/15216503/52616328-3935c580-2ebe-11e9-97b7-a9c567155720.png)

Forum fails with the below error:
![image](https://user-images.githubusercontent.com/15216503/52616412-70a47200-2ebe-11e9-86fa-87cddfefaef7.png)

CMS with below error:
![image](https://user-images.githubusercontent.com/15216503/52616445-8fa30400-2ebe-11e9-8806-370e8109770d.png)

**Comment by regisb** [comment]
This should be fixed by https://github.com/regisb/tutor/commit/486e5c57942d70bdf7f19d17da443f34ca4f679a

**Comment by nikhilrayaprolu** [comment]
@regisb Also the forum fails with this error
![image](https://user-images.githubusercontent.com/15216503/52628049-c0923180-2edc-11e9-91d4-8ec33c2b1359.png)

**Comment by regisb** [comment]
Isn't this fixed by running `tutor k8s databases`?
For now k8s is considered beta feature and I can't deliver fixes quickly. But it will work, eventually!
