### ISSUE TITLE
LMS in kubernetes throws Operational error as it couldn't connect to MySQL

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#167]
## Steps to reproduce
I tried fixing the #166 #164 by changing lms.env to ..aws
and by changing `stop(root)` to `stop()` but ended up with a new error as shown
![image](https://user-images.githubusercontent.com/15216503/52617938-6cc71e80-2ec3-11e9-8f43-a493781f2494.png)

**Comment by nikhilrayaprolu** [comment]
I think the issue is with the username.
We have set the password for `root` but not for the username `openedx`

**Comment by nikhilrayaprolu** [comment]
I finally found the answer,
we aren't running migrations in `tutor k8s quickstart`, so running `tutor k8s databases`, fixed the issue

**Comment by regisb** [comment]
@nikhilrayaprolu you are 100% right. I'll add the `databases` task to the quickstart. However, running migrations at that stage may fail, because the mysql/lms pods may not be ready. I'll add a warning.

**Comment by nikhilrayaprolu** [comment]
@regisb Maybe we could use lifecycles in that case?
https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by nikhilrayaprolu** [comment]
or can we just add a while loop that waits till the MySQL lifecycle turns to running and then start the next command?

**Comment by regisb** [comment]
Indeed, lifecycles could be a solution. I'll investigate that when I work on k8s again. For now I need to work on stabilizing tutor.

**Comment by nikhilrayaprolu** [comment]
Sure, @regisb , You stabilize the tutor, I will try testing kubernetes and make a pull request wherever required. :)
