### ISSUE TITLE
Error After Public Email

### ISSUE THREAD

**Issue by Gewgawrav** [regisb/tutor#171]
PLEASE PLEASE PLEASE READ THIS AND FOLLOW THE INSTRUCTIONS WHEN OPENING A NEW ISSUE

## Steps to reproduce

Run: tutor local quickstart

## Unexpected behavior

After asking for public email, system thrown be following error
![err](https://user-images.githubusercontent.com/46680667/52711157-16d3a300-2fb7-11e9-860b-0ce237427838.jpg)

**Comment by regisb** [comment]
Hi @Gewgawrav! It seems there is an incorrect version of `click`.

1. How did you install `tutor`?
2. What is the output of `pip freeze`?

**Comment by Gewgawrav** [comment]
Thanks for quick response @regisb !

1. * How did you install `tutor`?
- I installed it using pip3
`pip install tutor-openedx`

2. * What is the output of `pip freeze`?
![fgg](https://user-images.githubusercontent.com/46680667/52711939-2bb13600-2fb9-11e9-8f9a-38bbafee758d.jpg)

**Comment by Gewgawrav** [comment]
I have updated above comment.

**Comment by regisb** [comment]
Looks like `click` has been installed but does not have the proper version. You probably installed `python-click`. You should run tutor inside a virtualenv. Do you know how to do that?
