### ISSUE TITLE
tutor dev runserver lms error

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#172]
## Steps to reproduce

`tutor dev runserver lms` gives

![image](https://user-images.githubusercontent.com/15216503/52715432-77b4a880-2fc2-11e9-9e81-6810569626a8.png)

![image](https://user-images.githubusercontent.com/15216503/52715397-5fdd2480-2fc2-11e9-995a-a7cf6f8a59ea.png)

## Unexpected behavior

The output of the command should be 
`docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_dev run --rm -e SETTINGS=tutor.development --volume=/home/ubuntu/edx-platform:/openedx/edx-platform -p 8000:8000 lms ./manage.py lms runserver 0.0.0.0:8000`

**Comment by nikhilrayaprolu** [comment]
Upon running `docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_dev run --rm -e SETTINGS=tutor.development --volume=/home/ubuntu/edx-platform:/openedx/edx-platform -p 8000:8000 lms ./manage.py lms runserver 0.0.0.0:8000`
gives `RuntimeError: Model class openedx.core.djangoapps.theming.models.SiteTheme doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`
![image](https://user-images.githubusercontent.com/15216503/52715534-b0548200-2fc2-11e9-9934-973edc9a2ceb.png)

**Comment by regisb** [comment]
Thanks for raising this @nikhilrayaprolu! This will be fixes in v3.0.4, which will be ready in a few minutes.
