### ISSUE TITLE
Error in compilation of assets while using a custom edx platform

### ISSUE THREAD

**Issue by Ista2000** [regisb/tutor#174]
## Steps to reproduce

I ran the below commands in order.
1. `tutor dev run lms --edx-platform-path=/path/to/edx-platform /bin/bash`
2. `python setup.py install`
3. `python manage.py lms runserver --settings=tutor.development 0.0.0.0:8000`

I followed the above instructions after referring to the issue #173 

## Unexpected behavior

I'm getting 304 and 404 errors while trying to retrieve the static files. 
![image](https://user-images.githubusercontent.com/12626842/52913308-d2137900-32e2-11e9-8e5a-c7b805af6248.png)
Below is the final output.
![image](https://user-images.githubusercontent.com/12626842/52913358-739aca80-32e3-11e9-90b1-548f4e59ab19.png)

## Additional info (IMPORTANT)

Output of `tutor --version`: `tutor, version 3.0.5`

**Comment by Ista2000** [comment]
I also tried running the command `openedx-assets build` and got the following error
```
Traceback (most recent call last):
  File "/openedx/bin/openedx-assets", line 11, in <module>
    from pavelib import assets
ImportError: No module named pavelib
```

**Comment by Ista2000** [comment]
Ok, I solved the issue running `paver install_prereqs` before `openedx-assets build`.

**Comment by regisb** [comment]
Good job fixing this by yourself @Ista2000 :) You might also be interested in this recent change:
https://github.com/regisb/tutor/commit/b643a8719075927b62dea50c6b1104681455c330

And the corresponding documentation: http://docs.tutor.overhang.io/en/latest/dev.html#prepare-the-edx-platform-repo
