### ISSUE TITLE
In development Mode plugin missing error CMS

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#177]
In development mode, CMS is giving the plugin missing error, there is no error in installing through `tutor local`
![image](https://user-images.githubusercontent.com/15216503/54032253-1655b300-41d7-11e9-9e91-113ca1093356.png)

**Comment by regisb** [comment]
Hi @nikhilrayaprolu! Which command did you run, exactly? Generally speaking, when you open an issue, can you please try to follow the github issue template? It makes my life considerably easier :)

**Comment by nikhilrayaprolu** [comment]
this is the error I am receiving while I am trying to register a new course.
command I ran is `tutor dev runserver cms --edx-platform-path=/path/to/edx-platform`

**Comment by regisb** [comment]
Ok, so you are trying to mount a local repo. What is the version of that repo? Did you prepare the edx-platform repo, as described [here](https://docs.tutor.overhang.io/dev.html#prepare-the-edx-platform-repo)?

**Comment by nikhilrayaprolu** [comment]
Yes @regisb I prepared it, lms is working fine, CMS is giving the above error.

**Comment by regisb** [comment]
What is the version of the edx-platform repo? 

    cd /path/to/edx-platform
    git log -1

**Comment by nikhilrayaprolu** [comment]
```
commit 72fb572217fb17eb798632f4abdf88529deabbb0
Merge: 62b715a 918cae9
Author: Ned Batchelder <ned@nedbatchelder.com>
Date:   Tue Dec 11 10:07:01 2018 -0500

    Merge pull request #19413 from open-craft/josh/progress_data_block_hawthorn
    
    Put certificate data message into it's own block for overriding
```

It's on the hawthorn branch of the edx

**Comment by nikhilrayaprolu** [comment]
@regisb , I hope I found where the issue is,
Normally without mounting a new custom edx-platform, in the python console the command ` list(pkg_resources.iter_entry_points('xblock.v1'))`  gives

![image](https://user-images.githubusercontent.com/15216503/54068436-c3c9d480-4272-11e9-8031-ef695efe45ec.png)


On mounting a new custom edx-platform some of the packages are not available because the same above command gives:

![image](https://user-images.githubusercontent.com/15216503/54068451-d8a66800-4272-11e9-88c4-556e881790f1.png)


On observing the base.txt and development.txt requirements files in edx-platform, I found that there are some relative links to the packages like:  `-e common/lib/xmodule`
so I thought of reinstalling the packages by running `paver install_prereqs` which gave a command `pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/development.txt`, upon which again the above missing packages are available.

**Comment by regisb** [comment]
@nikhilrayaprolu You nailed it :) Basically, you need to install the development settings. You can do so by running:
    
    tutor dev run --edx-platform-path=/path/to/edx-platform lms pip install --src ../venv/src --requirement requirements/edx/development.txt

I'll update the documentation. There are a few other minor issues related to `dev` commands that will be fixed in the next release.

**Comment by nikhilrayaprolu** [comment]
I think only
`pip install -e common/lib/dogstats/ common/lib/safe_lxml/ common/lib/sandbox-packages/ common/lib/symmath/ common/lib/xmodule/` is sufficient?

**Comment by regisb** [comment]
Yes, probably.
