### ISSUE TITLE
Viewing as Learner in Audit isn't the same as a real learner in Audit

### ISSUE THREAD

**Issue by frohro** [regisb/tutor#181]
## Steps to reproduce
I don't know if all these steps are necessary to reproduce this, but here is what I remember of what happened before I discovered this problem.
- Make an assignment in studio.
- Have a learner do the assignment.
- Duplicate the problem.
-. Go and try to rescore the assignment and reset the number of tries taken to zero.
- Make the first assignment invisible to the learners.
- Go look for the second assignment as a learner in audit.  Note that it seems to work.
- Get the learner to do the same.  They can't load the page, however if they use the right arrow to scroll to the right, it appears they can scroll past the first assignment and get to the second.  It doesn't appear that way for the professor trying to view as a learner in audit.  I don't think the audit makes any difference, as I think learner is the same.
## Additional info (IMPORTANT)

I'm still using the Makefile version.

**Comment by regisb** [comment]
Hi @frohro! I'll try to reproduce this; meanwhile, can you please try to create a separate, empty platform with tutor v3, just to make sure that the bug still happens in the latest version?

**Comment by regisb** [comment]
And can you please do the same with issue #180?

**Comment by regisb** [comment]
Closing, as well as #180. Please re-open if you feel this is still an issue with the most recent tutor release and it's not related to an upstream Open edX bug.
