### ISSUE TITLE
Video Speed Up not Working Within edX

### ISSUE THREAD

**Issue by frohro** [regisb/tutor#182]
## Steps to reproduce

- In studio add a video from youtube.
- While still in studio, try to watch that video at higher (or lower) speed.  Observe the results.
- Go to the live version, and try the same.  Observe the results.
## Unexpected behavior

The video speed is not adjusted in either case.  

If you go to youtube the speedup works fine.  
## Additional info (IMPORTANT)

Still the makefile version, as I haven't been able to get the upgrade or clean install to work yet.

**Comment by regisb** [comment]
Unfortunately, I managed to reproduce this issue in Open edX using the official Devstack on Hawthorn. That means that it's a bug in Open edX. This bug might be related to https://openedx.atlassian.net/browse/PLAT-2423
For other video playback speed-related issues, please take a look at https://openedx.atlassian.net/secure/QuickSearch.jspa?searchString=video%20speed
