### ISSUE TITLE
how change the default encode using utf8?

### ISSUE THREAD

**Issue by JerryKuan** [regisb/tutor#183]
when I want to export the course that I created,something happened  like the statement "'ascii' codec can't encode characters in position 32-33: ordinal not in range(128)". I think maybe is the encode problem. So I want to change the default encode from ascii to utf8,how can I solve it?

**Comment by regisb** [comment]
Hi @JerryKuan! Please run the following command right after triggering the error, and post the output here:

    tutor local logs --tail=200

This will capture the full stacktrace, which we'll use to better understand the problem.

**Comment by regisb** [comment]
@JerryKuan Did you manage to solve the problem?

**Comment by JerryKuan** [comment]
no, when i execute the command. I get many error. I don't know how to select the right infomation. I select two statement 
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (111)")
forum_1            | /openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:52: warning: constant ::Fixnum is deprecated . I don't know how to fix it.

**Comment by regisb** [comment]
I'm afraid I need the full stacktrace in order to debug. I suggest you run the following command right after you trigger the error:

    tutor local logs --tail=200 > ~/issue183.log

And then post here the content of file `issue183.log`.

**Comment by JerryKuan** [comment]
when I stop server, and restart it ,I find django can't connect mysql, and the tips is django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (111)"). then i execute your command, i find nothing output. Thanks for your help.

**Comment by regisb** [comment]
Did you manage to setup a basic, working platform with `tutor local quickstart`?

**Comment by JerryKuan** [comment]
yes, and I have deployed a course on the platform.

**Comment by regisb** [comment]
Please do the following:

1. Paste here the output of `tutor --version`
2. `tutor local stop`
3. Paste here the output of `docker ps`
4. `tutor local pullimages`
5. `tutor local start-daemon`
6. Attempt to export your course
7. Immediately after you triggered the error: `tutor local logs --tail=200 > ~/issue183.log`
8. Paste here the content of file `issue183.log`.

**Comment by dannielarriola** [comment]
I had the same issue ('ascii' codec can't encode characters in position 32-33: ordinal not in range(128))
In my case, this was caused by special characters in upload file names.
I tried to change default charset too, but it dont work. I finally  had to delete those file and upload again without special characters

**Comment by JerryKuan** [comment]
I have uninstall the server. and ready install the newest version. the version of docker-compose lasted use is 1.18 , but it doesn't work. I want to know the newest tutor  need which version of docker-compose?

**Comment by JerryKuan** [comment]
I reinstalled the server, then changed the file naming method and solved the problem that the course could not be exported.Sincerely thanks！

**Comment by regisb** [comment]
That's great. Thanks @dannielarriola for the support!
