### ISSUE TITLE
Need to be able to change subnets used by docker tor resolve conflicts...

### ISSUE THREAD

**Issue by frohro** [regisb/tutor#184]
ip -a shows that tutor is using a bunch of IP addresses that are already in use on campus.  I need to be able to select the range of IP addresses used, so users on campus can get to tutor.

**Comment by regisb** [comment]
Hi @frohro! This is a feature that is supported by docker directly, so there is no need to modify tutor to change the subnet addresses. Have you already tried to do something like this? https://linuxctl.com/2016/02/docker-networking---change-docker0-subnet/

This information might be useful to others. So, if the above link solves your issue, I'll include it in the tutor documentation. Can you please try it out and tell me the results?

**Comment by frohro** [comment]
Hi Regis,
Before I filed this, I did the /etc/docker/daemon.json, but it didn't change a thing.  I don't know what the deal is.
Thanks,
Rob

**Comment by regisb** [comment]
I managed to solve this by creating the tutor network manually:

```
tutor local stop
docker network rm tutor_local_default
docker network create --subnet 182.18.0.100/16 tutor_local_default
tutor local start
```

**Comment by frohro** [comment]
The above works for me too.
Thanks,
Rob
