### ISSUE TITLE
migrating theme to tutor v 3.0.6

### ISSUE THREAD

**Issue by JeffKatzy** [regisb/tutor#185]
I have been actively developing a theme with the previous version of tutor, and tried to migrate over to the most recent version via [the following](https://docs.tutor.overhang.io/local.html#upgrading-from-earlier-versions).

I am unable to import my theme (which worked in the previous version).

## Steps to reproduce

`export TUTOR_ROOT=/Users/jeff/software/env-tutor`  (set to current working directory)
`tutor local quickstart`

`mkdir -p $(tutor config printroot)`
`mv config.json data/ $(tutor config printroot)`
 -> Folder data already exists 
So I removed the data folder from $TUTOR_ROOT
`rm -rf data/`
`mv data/ $(tutor config printroot)`

`tutor local quickstart` 
This migrated my .json file to .yml

## Unexpected behavior
Looking at the [https://docs.tutor.overhang.io/dev.html?highlight=custom%20theme](documentation) on custom theming, it mentions moving to the `env/build/openedx/themes` folder, but I did not have a `build` folder in the $TUTOR_ROOT/env directory.
`ls env`
`apps local`

So I moved the build folder from the tutor repo's [templates directory](https://github.com/regisb/tutor/tree/master/tutor/templates/build) `env` folder, then I added the theme to the `build/openedx/themes` directory. 

I get the following error message: 

```
019-03-18 18:54:30,664 ERROR 117 [openedx.core.djangoapps.theming.helpers] helpers.py:224 - Theme not found in any of the themes dirs. [Theme 'gymnasium-edx-theme' not found in any of the following themes dirs,
Theme dirs:
[Path(u'/openedx/themes')]]
Traceback (most recent call last):
  File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 219, in get_current_theme
    themes_base_dir=get_theme_base_dir(site_theme.theme_dir_name),
  File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 260, in get_theme_base_dir
    dir=get_theme_base_dirs(),
ValueError: Theme 'gymnasium-edx-theme' not found in any of the following themes dirs,
Theme dirs:
[Path(u'/openedx/themes')]
```

And the theme does not add.  I also tried creating an `openedx/themes/gymnasium-edx-theme` to my $TUTOR_ROOT directory, and placing my theme in there, but that also did not work. 

## Additional info (IMPORTANT)

`tutor, version 3.0.6`

**Comment by regisb** [comment]
Hi @JeffKatzy! Thanks for taking the time to open this issue. I suspect this is an older bug related to b7c31d770f39dece8878800c1094197868519176

Please do the following:

1. Upgrade to the latest tutor version (3.1.0)
2. Update your environment: `tutor local env`
3. Paste here the output of `ls $(tutor config printroot)/env/build/openedx/themes`
4. Stop any running platform: `tutor local stop`
5. Run in development mode: `tutor runserver dev`

Is your theme available after running the above steps?

**Comment by JeffKatzy** [comment]
That did the trick!

In other news, I have also begun developing locally with with the updated tutor version, and that's gone smoothly, so far.. :)

**Comment by regisb** [comment]
Awesome! Please let me know how local development is going, by email or in person if you are planning on going to the Open edX conference next week.
