### ISSUE TITLE
Course Search - displays results in triples

### ISSUE THREAD

**Issue by micahl98** [regisb/tutor#189]
Steps:

1. Install IronWood with Tutor.
2. Create two coures
3. Browse course listings

Result: displays the 2 courses, 3 times.

Ref.: Régis Behmo 
AFAIU this is an upstream issue that was introduced in https://github.com/edx/edx-platform/commit/c746a4e6305.

The course listing is *not* performed by the `courses` view in edx-platform, but by the js view in `courses_listing.js` (and thus by edx-search with the `elastic.py` basckend). This js view is responsible for filling the course list not once, but three times.
(sorry if this doesn't make sense to you. I'm writing this down mostly for myself so that I can open a documented issue upstream later)

I find it surprising that this has worked at all before and that no one noticed it during the ironwood beta.

GitHub
Add Journals support · edx/edx-platform@c746a4e
Enable the journal app in LMS. Add support to display Journals on index and courseware pages and dashboard.

**Comment by regisb** [comment]
I confirm that this is an upstream edx-platform bug, as I managed to reproduce it in the devstack. A Jira ticket has been opened: https://openedx.atlassian.net/browse/LEARNER-7210

I don't feel so confident creating a PR about this, so maybe I'll just deactivate course search for now. Would that work for you @micahl98 ?

**Comment by micahl98** [comment]
We do actually need the course search working for the product we are creating; its OK to leave it broken for now until the upstream fix does the repair.

**Comment by regisb** [comment]
:+1:

**Comment by regisb** [comment]
https://github.com/edx/edx-platform/pull/20325 If this is not merged into ironwood, we will pull the patch into the tutor image.

**Comment by regisb** [comment]
@micahl98 The patch will be added to the next tutor release
