### ISSUE TITLE
Not showing new theme after compile assets

### ISSUE THREAD

**Issue by linkmoises** [regisb/tutor#191]
I'm developing a new theme for my Open edX instance and it's activated in the django panel. When I use any of the [stanford template](https://github.com/Stanford-Online/openedx-themes) it is displayed correctly; however, when using my new template it is not displayed on the site. At this point, I'm only expecting to see the logo change. I have not added the scss files yet.

## Steps to reproduce

`$ git clone https://github.com/linkmoises/mdx-edx.git $(tutor config printroot)/env/build/openedx/themes/`

`$ tutor images build openedx`

I can see some warnings at this point, but the assets are compiling compiling sucessfully.

```
rtlcss /openedx/themes/docenciamd/lms/static/css/discussion/lms-discussion-bootstrap.css /openedx/themes/docenciamd/lms/static/css/discussion/lms-discussion-bootstrap-rtl.css
rtlcss: Warning! No config present, using defaults.
Saving: /openedx/themes/docenciamd/lms/static/css/discussion/lms-discussion-bootstrap-rtl.css
rtlcss /openedx/themes/docenciamd/lms/static/css/bootstrap/lms-main.css /openedx/themes/docenciamd/lms/static/css/bootstrap/lms-main-rtl.css
rtlcss: Warning! No config present, using defaults.
Saving: /openedx/themes/docenciamd/lms/static/css/bootstrap/lms-main-rtl.css
Compiling cms sass assets from theme /openedx/themes/docenciamd...
```

## Unexpected behavior

The new theme is not showing. I can see this error message showing recurrently in the log

```
lms_1             | Theme dirs: 
lms_1             | [Path(u'/openedx/themes')]]
lms_1             | Traceback (most recent call last):
lms_1             |   File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 220, in get_current_theme
lms_1             |     themes_base_dir=get_theme_base_dir(site_theme.theme_dir_name),
lms_1             |   File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 261, in get_theme_base_dir
lms_1             |     dir=get_theme_base_dirs(),
lms_1             | ValueError: Theme 'docenciamd' not found in any of the following themes dirs, 
lms_1             | Theme dirs: 
lms_1             | [Path(u'/openedx/themes')]
```

## Additional info

Tutor, version 3.3.3

Regards from Panama!!

**Comment by regisb** [comment]
Hi @linkmoises! Sorry for the delay, I'm currently on holiday with little Internet access.
Just to be sure, did you stop and start the platform after rebuilding the image? (don't use the restart command, it's not working as expected)

**Comment by linkmoises** [comment]
Oh! It works in this way as you say, `tutor local stop` and `tutor local start`.
