### ISSUE TITLE
Studio Login not working

### ISSUE THREAD

**Issue by ProtoBrunch** [regisb/tutor#193]
As discussed today in [this forum post](https://discuss.overhang.io/t/studio-login-not-working/32),
I'm opening an Issue regarding the broken Studio Login.

To quickly elaborate: When setting up a new platform, if SSL-Encryption has been chosen during the installation process, the login into CMS doesn't work.
The user gets redirected to the LMS login and can enter her credentials, but upon getting back to the CMS, the User is still not logged in.

To work around this, I placed
"SESSION_COOKIE_DOMAIN": "my.root.domain.com",
into the lms.env.json-file and restarted the platform.

**Comment by regisb** [comment]
Thanks @ProtoBrunch! Did the proposed fix solve the issue?

**Comment by ProtoBrunch** [comment]
Yes, login into cms works now.

**Comment by regisb** [comment]
@ProtoBrunch thanks for the thorough reporting! The fix will be available in the next release (3.3.4) of tutor.
