### ISSUE TITLE
How to delete the redundant container or image of the previous version

### ISSUE THREAD

**Issue by JerryKuan** [regisb/tutor#196]
hi,I want to know if the previous containers or images is still in memory after I updated the version. If it is, it definitely takes up a lot of space. How do I delete the redundant containers or images of the previous version?my present version is 3.3.thanks!

**Comment by regisb** [comment]
That's an easy one :) https://docs.docker.com/engine/reference/commandline/image_prune/

    docker image prune

PS: for such questions, the forums may be better adapted https://discuss.overhang.io/
