### ISSUE TITLE
What is smallest setup for dev only work?

### ISSUE THREAD

**Issue by weisisheng** [regisb/tutor#200]
Right now getting familiarized for a small test.

Very interested in the Amazon AMI setup but only need for development (out of country).  My main production server is in mainland China and doesn't have access to the AMI.  I don't want to go through hassle of multistep process to move it (the AMI). Assuming I get an interesting course created, I would need to migrate content to the country.

What is the smallest AWS setup for testing and development, less than 3-5 students max?

**Comment by regisb** [comment]
Hi @weisisheng! The smallest supported AWS image is t2.medium: that's the minimum necessary to run the database migrations, which require 4Gb RAM https://docs.tutor.overhang.io/install.html#requirements

(I'm closing this issue, but feel free to add comments. For questions such as this one, the discussion forums may be more appropriate: https://discuss.overhang.io/)
