### ISSUE TITLE
Additional XBlocks not enabled

### ISSUE THREAD

**Issue by travlr** [regisb/tutor#203]
XBlocks I attempt to install are not available in the cms

I am researching the cause of this issue now and will report my progress. 

## Steps to reproduce

1. `tutor local stop`
2. Add github repository for XBlock to "private.txt": `echo "git+https://github.com/openedxou/print-xblock.git" >> $(tutor config printroot)/env/build/openedx/requirements/private.txt`
3. `tutor config save -y`
4. `tutor images build openedx`
5. `tutor local databases`
6. `tutor local start`

## Unexpected behavior

In studio, I enable the XBlock in Settings > Advanced Settings > Advanced Module List. 

In the Outine under "Unit" >> "Add New Component  >> "Advanced" ..the XBlock is not displayed in the combo-box.

## Additional info (IMPORTANT)

tutor, version 3.3.4

[lms-log.txt](https://github.com/regisb/tutor/files/3104383/lms-log.txt)
[cms-log.txt](https://github.com/regisb/tutor/files/3104384/cms-log.txt)

**Comment by regisb** [comment]
Hi @travlr! The `private.txt` requirements file is overwritten whenever you run `tutor config save`. Try the same process without step 3 and it should work fine.

**Comment by travlr** [comment]
Hi @regisb .. It does not seem to be the problem, but I'm in a meeting at them moment and will investigate more thoroughly later.  I believe that even though the configuration is set in "private.txt".. it is not installing into the image.

**Comment by travlr** [comment]
The issue was resolved with a little more understanding of the process. Thanks Regis :)

**Comment by regisb** [comment]
that's great news :) would you clarify the docs in any way?

**Comment by travlr** [comment]
Yes, I'd be happy too. I'll get to it soon! :)
