### ISSUE TITLE
LMS/CMS gunicorn processes use too much RAM

### ISSUE THREAD

**Issue by regisb** [regisb/tutor#207]
## Steps to reproduce

    tutor local quickstart

## Unexpected behavior

LMS and CMS use a lot of resources, processes start swapping, and accessing the LMS/CMS fro the browser results in 504 errors (Gateway time-out).

## Additional info (IMPORTANT)

All versions post v3.3.5 are affected. I'm running this on a laptop with 4 CPU and 8 Gb RAM.

@silviot this is due to PR #197. On my laptop, the LMS and CMS become totally unusable because they use too much resources. On what type of configuration did you test this?

It's hard to evaluate how much RAM each gunicorn worker uses. I manage to get by with 1, 2 or 4 but not 6 or 9 workers.

Given that tutor is supposed to [require only 4 Gb RAM to run](https://docs.tutor.overhang.io/install.html#requirements), I'm going to have to reduce the number of workers. I suggest reducing it to just the number of CPU: `workers = (multiprocessing.cpu_count()`

Given that both the LMS and the CMS need to run at the same time, this seems more reasonable.

What do you think @silviot?

**Comment by regisb** [comment]
@silviot I closed this to release v3.3.8 but feel free to comment on the compromise that I made.

**Comment by silviot** [comment]
I didn't realize it was spawning so many processes. On an 8 core machine that's 34. A bit too many.
I think the important thing is to have more than one worker (in some cases the LMS needs to do http calls to itself), and that it's a configurable value. So the current solution looks good: one can always override the number of workers from the `command`.
Consider though making the minimum number 2: `max(multiprocessing.cpu_count(), 2)`.
