### ISSUE TITLE
a tool for Kubernetes HTTPS certificates

### ISSUE THREAD

**Issue by wwj718** [regisb/tutor#214]
Hi regisb,  [cert-manager](https://github.com/jetstack/cert-manager) may be useful to HTTPS certificates(Kubernetes)

[cert-manager](https://github.com/jetstack/cert-manager): Automatically provision and manage TLS certificates in Kubernetes

## Steps to reproduce
N/A

## Unexpected behavior
N/A

## Additional info (IMPORTANT)
N/A

**Comment by regisb** [comment]
Hey @wwj718, thanks for the info! I expect that the choice of the tool for SSL certificate generation will be left to the cluster maintainer, but I'll keep cert-manager in mind for the k8s rewrite that I'm currently doing.
