### ISSUE TITLE
v3.4 k8s quickstart fails

### ISSUE THREAD

**Issue by bvanhou** [regisb/tutor#223]
command ran: `tutor k8s quickstart`

currently solution: reverted to 3.3 

Stack:
```
unknown flag: --kustomize
Error: Command failed with status 1: kubectl apply --kustomize /Users/user/Library/Application Support/tutor/env --wait --selector app.kubernetes.io/component=namespace
```

**Comment by regisb** [comment]
Hi @bvanhou! This seems to be related to your version of `kubectl`. `--kustomize` is supported starting from v1.14: https://kubernetes.io/blog/2019/03/25/kubernetes-1-14-release-announcement/
Are you able to upgrade your client?

**Comment by bvanhou** [comment]
I am on version 1.15 but I will double check.

**Comment by regisb** [comment]
This is strange. What is the output of `kubectl version`?

**Comment by bvanhou** [comment]
v1.15 I am uninstalling kubectl and starting fresh. Maybe there is an issue with a previous version being referenced
