### ISSUE TITLE
How can I add analytics feature?

### ISSUE THREAD

**Issue by dannielarriola** [regisb/tutor#58]
## Steps to reproduce
I want to add the following features to this stack

* https://github.com/edx/edx-analytics-dashboard
* https://github.com/edx/edx-analytics-data-api
* https://github.com/edx/edx-analytics-pipeline

How can I achieve this working wiht containers?

**Comment by regisb** [comment]
Hi @dannielarriola,
Brace yourself! The analytics stack is notoriously the most complex part of Open edX to setup. There is little to no instruction on how to set it up manually; instead, you should read the Ansible playbooks from the [configuration](https://github.com/edx/configuration) repo and convert the instructions to Dockerfiles. I attempted this once, but quit after users told me they don't have much interest for the analytics stack. And I'll be happy to process take pull requests on this! Alternatively, if you or your company are willing to financially sponsor this development, I can try to do it again.

**Comment by dannielarriola** [comment]
Hi @regisb,
Thanks for you answer,
I try to do this once too, but it was really difucult to me and I didn't make it.
I will consult with my company if they are interested in sponsor this development, it would be very helpful

**Comment by frohro** [comment]
Is there a way to get export grade data from edX to a spread sheet or something without the analytics package?  I can't figure out how to even get the class average on an assignment, short of getting my calculator out and figuring it out by hand.  :-)  Am I missing it somewhere?
Thanks!
Rob

**Comment by frohro** [comment]
On this page, it claims you can click "Data Download," but I don't have that option.
https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/named-release-birch/running_course/course_grades.html

**Comment by frohro** [comment]
Correction:  I meant "Generate Grade Report."  I do have Data Download, but not the grade report opiton.  The CSV anonymized IDs has no grade data.
Thanks,
Rob

**Comment by regisb** [comment]
@frohro I have no idea :-/ this is an Open edX-specific issue which is not directly related to openedx-docker... The link you mentioned is from the Birch release, which is extremely old. You need to find the information in the Hawthorn docs: https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/index.html
Also, please don't add comments on this issue, which is not directly related to your question! Participants all receive a notification. Thanks :wink:

**Comment by dannielarriola** [comment]
Hi @regisb 
How I can sponsor this development?
Can this be in a private repository?

**Comment by frob** [comment]
Sorry, why private? I could see if this was custom logic. But as a feature as generic and useful as analytics, it would serve the community better to sponsor this in the open.

**Comment by regisb** [comment]
This has been open for too long, and I'm pretty sure I'm not going to integrate Analytics to Tutor. If I ever do, it will be under the form of a plugin. Meanwhile, [Figures](https://github.com/appsembler/figures) looks more promising.
