### ISSUE TITLE
Android Signin Error

### ISSUE THREAD

**Issue by frohro** [regisb/tutor#89]
To duplicate:

    make android

Transfer the .apk to an android phone (I'm using Android 8.0 and an LG G5 (h830)).
Install the .apk.
Open the .apk.
Try to sign in with credentials that work on a web browser.
Get a message, "Sign-in Error Unknown error.  Please try again later.  
Hit the OK message.
On the server do a docker-compose logs -f
Here is the output:

```
lms_1            | 2018-11-08 06:22:47,557 INFO 238 [tracking] logger.py:50 - {"username": "", "event_type": "/oauth2/access_token/", "ip": "172.19.0.1", "agent": "Dalvik/2.1.0 (Linux; U; Android 8.0.0; LG-H830 Build/OPR1.170623.032) WWU Open edX/com.example.yourapp/2.15.1", "host": "edx.fweb.wallawalla.edu", "referer": "", "accept_language": "", "event": "{\"POST\": {\"username\": [\"rob.frohne@wallawalla.edu\"], \"password\": \"********\", \"grant_type\": [\"password\"]}, \"GET\": {}}", "event_source": "server", "context": {"user_id": null, "org_id": "", "course_id": "", "path": "/oauth2/access_token/"}, "time": "2018-11-08T06:22:47.557388+00:00", "page": null}
lms_1            | 2018-11-08 06:22:47,670 ERROR 238 [edx_oauth2_provider.forms] forms.py:115 - OAuth2: Client ID 'None' does not exist.
lms_1            | Traceback (most recent call last):
lms_1            |   File "/usr/local/lib/python2.7/dist-packages/edx_oauth2_provider/forms.py", line 112, in clean
lms_1            |     client = Client.objects.get(client_id=data.get('client_id'))
lms_1            |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
lms_1            |     return getattr(self.get_queryset(), name)(*args, **kwargs)
lms_1            |   File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 380, in get
lms_1            |     self.model._meta.object_name
lms_1            | DoesNotExist: Client matching query does not exist.
nginx_1          | 172.19.0.1 - - [08/Nov/2018:06:22:47 +0000] "POST /oauth2/access_token/ HTTP/1.1" 400 27 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; LG-H830 Build/OPR1.170623.032) WWU Open edX/com.example.yourapp/2.15.1" "174.127.180.10"
```

**Comment by regisb** [comment]
This is a hard one... The Android app is built from inside Docker, but there is currently no configuration for this app. Some manual steps are required, but I currently have no idea what they are. I'll leave this issue open and take some time to experiment.

**Comment by frohro** [comment]
Thanks Regis,
I thought maybe my students might prefer it to using the browser in their phones for those who are using Andriod phones.  :-)
Again, thanks so much for all the support!
Rob

**Comment by kbitr** [comment]
I can confirm this error. But I appears everywhere; login, password reset, new account.

**Comment by regisb** [comment]
I am happy to tell you that this issue is now fixed! You can generate the app with:

```
tutor android env
tutor local databases
tutor android build debug
```

**Comment by frohro** [comment]
Wow!  Thanks Regis!
Rob

**Comment by regisb** [comment]
@kbitr @frohro maybe you noticed, I created a discussion forum for Tutor: https://discuss.overhang.io
I just posted a topic about the Android app: https://discuss.overhang.io/t/android-app-now-truly-ready-for-testing-o/12 ,aybe you can pitch in?
